# api/swagger.yaml
openapi: 3.0.0
info:
  title: Auth Service API
  description: API for user authentication and registration
  version: 1.0.0
paths:
  /health:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: UP
                  service:
                    type: string
                    example: auth-service
                  version:
                    type: string
                    example: 1.0.0
  /auth/register:
    post:
      summary: Register a new user
      description: Register a new user and send verification email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - phone
                - password
              properties:
                email:
                  type: string
                  format: email
                phone:
                  type: string
                password:
                  type: string
                  format: password
      responses:
        '201':
          description: Registration successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  message:
                    type: string
        '400':
          description: Invalid request
        '409':
          description: User already exists
        '500':
          description: Server error